import "@coinbase/onchainkit/styles.css";
import "@rainbow-me/rainbowkit/styles.css";
import "./globals.css";

import { Header } from "@/app/_components/header";
import { cn } from "@/shared/utils/tailwind";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Fairpay",
  description: "Generated by create next app",
};

const OnchainProviderNoSSR = dynamic(
  () => import("@/shared/providers/onchain-provider").then((mod) => mod.OnchainProvider),
  { ssr: false }
);

export const viewport = {
  width: "device-width",
  initialScale: 1.0,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(inter.variable, "min-h-screen h-full")}
      style={{ scrollbarGutter: "stable" }}
    >
      <body className={"w-full h-full flex flex-col"}>
        <OnchainProviderNoSSR>
          <Header />
          {children}
        </OnchainProviderNoSSR>
      </body>
    </html>
  );
}
