import { Header } from "@/shared/components/header";
import { cn } from "@/shared/utils/tailwind";
import type { Metadata } from "next";
import { Crimson_Text } from "next/font/google";
import "./globals.css";

const crimson = Crimson_Text({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lexend',
  weight: ['400', '600', '700'],
 });

export const metadata: Metadata = {
  title: "Fairpay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-screen min-h-screen">
      <body className={cn(crimson.className,'w-full h-full')}>
        <Header />
        {children}</body>
    </html>
  );
}
